---
openapi: 3.0.3
info:
  title: Stock of Products of a Supplier
  version: v1
servers:
- url: catenax.io/api/v1
  variables:
    api-version:
      default: v1
paths:
  /{tenant-id}/product-stock:
    get:
      tags:
      - ProductStock
      operationId: getProductStock
      parameters:
      - name: tenant-id
        in: path
        description: The ID of the tenant owning the requested Twin.
        required: true
        schema:
          type: string
          format: uuid
      - name: start
        in: query
        description: Starting index which is starting by 0
        required: false
        schema:
          type: number
      - name: count
        in: query
        description: Number of items to return per call.
        required: false
        schema:
          type: number
      - name: totalItemCount
        in: query
        description: Flag that indicates that the total counts should be returned.
        required: false
        schema:
          type: boolean
      responses:
        "200":
          $ref: '#/components/responses/ProductStock'
        "401":
          $ref: '#/components/responses/ClientError'
        "402":
          $ref: '#/components/responses/Unauthorized'
        "403":
          $ref: '#/components/responses/Forbidden'
        "404":
          $ref: '#/components/responses/NotFoundError'
components:
  schemas:
    ErrorResponse:
      type: object
      required:
      - error
      properties:
        error:
          $ref: '#/components/schemas/Error'
    Error:
      type: object
      required:
      - details
      properties:
        message:
          type: string
          minLength: 1
        path:
          type: string
          minLength: 1
        details:
          type: object
          minLength: 1
          additionalProperties:
            type: object
        code:
          type: string
          nullable: true
    PagingSchema:
      type: object
      properties:
        items:
          type: array
          items:
            $ref: '#/components/schemas/ProductStock'
        totalItems:
          type: number
        totalPages:
          type: number
        pageSize:
          type: number
        currentPage:
          type: number
    urn_samm_io.catenax.product_stock_1.0.0_OrderIdCharacteristic:
      type: string
      description: "This is a proprietary order ID, generated by either the supplier\
        \ side or customer side."
    urn_samm_io.catenax.product_stock_1.0.0_OrderPositionIdCharacteristic:
      type: string
      description: The position ID is unique for an order and used within business
        context to refer to a position.
    urn_samm_io.catenax.product_stock_1.0.0_OrderPositionReferenceCharacteristic:
      description: "The order position reference includes reference numbers for the\
        \ order and the ID. As these information are meant for the customer, the customer\
        \ reference numbers are mandatory."
      type: object
      properties:
        supplierOrderId:
          description: "This is the order number on the supplier side that is given\
            \ by e.g., the supplier's enterprise resource planning system."
          $ref: '#/components/schemas/urn_samm_io.catenax.product_stock_1.0.0_OrderIdCharacteristic'
        customerOrderId:
          description: "This is the order number on the customer side that can be\
            \ given by e.g., the customer's enterprise resource planning system."
          $ref: '#/components/schemas/urn_samm_io.catenax.product_stock_1.0.0_OrderIdCharacteristic'
        customerOrderPositionId:
          description: "This is an identifier for the position of an order defined\
            \ by the customer. It's not a technical identifier, such as an UUID. This\
            \ identifier is used within the business context when talking about the\
            \ position."
          $ref: '#/components/schemas/urn_samm_io.catenax.product_stock_1.0.0_OrderPositionIdCharacteristic'
      required:
      - customerOrderId
      - customerOrderPositionId
    urn_samm_io.catenax.product_stock_1.0.0_DateTimeStamp:
      type: string
      format: date
      description: The Date with the the timezone of the involved site.
    urn_samm_io.catenax.product_stock_1.0.0_NumberofObjects:
      type: number
      description: Quantifiable number of objects in reference to the measurementUnit
    urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_UnitReference:
      type: string
      pattern: "[a-zA-Z]*:[a-zA-Z]+"
      description: Describes a Property containing a reference to one of the units
        in the Unit Catalog.
    urn_samm_io.catenax.product_stock_1.0.0_QuantityCharacteristic:
      description: Describes the quantity in which the child part is assembled in
        the given parent object by providing a quantity value and the measurement
        unit in which the quantity is measured.
      type: object
      properties:
        quantityNumber:
          description: The number of objects related to the measurement unit
          $ref: '#/components/schemas/urn_samm_io.catenax.product_stock_1.0.0_NumberofObjects'
        measurementUnit:
          description: |-
            Unit of measurement for the quantity of objects.
            If possible, use units from the aspect meta model unit catalog, which is based on the UNECE Recommendation No. 20 "Codes for Units of Measure used in International Trade".
          $ref: '#/components/schemas/urn_samm_org.eclipse.esmf.samm_characteristic_2.1.0_UnitReference'
      required:
      - quantityNumber
      - measurementUnit
    urn_samm_io.catenax.product_stock_1.0.0_LocationIdTypeEnum:
      type: string
      description: Enumeration specifying types of keys for locations within Catena-X.
      enum:
      - BPNS
      - BPNA
    urn_samm_io.catenax.product_stock_1.0.0_LocationIdCharacteristic:
      type: string
      description: The actual key based on the type.
    urn_samm_io.catenax.product_stock_1.0.0_SupplierStockLocationIDCharacteristic:
      description: This is the location where the stock is located.
      type: object
      properties:
        locationIdType:
          description: Type of the location's ID.
          $ref: '#/components/schemas/urn_samm_io.catenax.product_stock_1.0.0_LocationIdTypeEnum'
        locationId:
          description: The actual ID reflecting the type (locationIdType) of the location.
          $ref: '#/components/schemas/urn_samm_io.catenax.product_stock_1.0.0_LocationIdCharacteristic'
      required:
      - locationIdType
      - locationId
    urn_samm_io.catenax.product_stock_1.0.0_AllocatedStock:
      description: This is the quantity of already produced goods at a given location
        that has not yet been shipped. The allocated stock is the stock available
        for the customer and may refer to a given position (see OrderPositionReference).
        Quantities of Materials belonging to this stock are not available for other
        positions or customers. This stock consists only of the good parts.
      type: object
      properties:
        quantityOnAllocatedStock:
          description: This is the quantity of the material within the position that
            is already ready to be delivered.
          $ref: '#/components/schemas/urn_samm_io.catenax.product_stock_1.0.0_QuantityCharacteristic'
        supplierStockLocationId:
          description: One stock has always one location. The location is identified
            using BPNs. The location can be identified differently depending on the
            partner.
          $ref: '#/components/schemas/urn_samm_io.catenax.product_stock_1.0.0_SupplierStockLocationIDCharacteristic'
      required:
      - quantityOnAllocatedStock
      - supplierStockLocationId
    urn_samm_io.catenax.product_stock_1.0.0_AllocatedStockCollection:
      description: Collection of AllocatedStocks that may relate to different supplierStockLocations.
      type: array
      items:
        $ref: '#/components/schemas/urn_samm_io.catenax.product_stock_1.0.0_AllocatedStock'
    urn_samm_io.catenax.product_stock_1.0.0_Position:
      description: The Position can be located at several stocks. A position may be
        anonymous or may reference an position within an order.
      type: object
      properties:
        orderPositionReference:
          description: The order position reference contains information to identify
            a position within an order.
          $ref: '#/components/schemas/urn_samm_io.catenax.product_stock_1.0.0_OrderPositionReferenceCharacteristic'
        lastUpdatedOnDateTime:
          description: Date and time at which the position has been updated by the
            supplier's systems. Date and time are set according to a timezone.
          $ref: '#/components/schemas/urn_samm_io.catenax.product_stock_1.0.0_DateTimeStamp'
        allocatedStocks:
          description: Stocks already allocated to the customer. There is one AllocatedStock
            per supplierStockLocation.
          $ref: '#/components/schemas/urn_samm_io.catenax.product_stock_1.0.0_AllocatedStockCollection'
      required:
      - lastUpdatedOnDateTime
      - allocatedStocks
    urn_samm_io.catenax.product_stock_1.0.0_PositionsCollection:
      description: "If any stock is available, then there is at least one position.\
        \ If the supplier does differentiate the stock according to the order positions\
        \ (an OrderPositionReference is set), then multiple positions can be given.\
        \ There could also be only one position without an OrderPositionReference\
        \ indicating an anonymous stock which is allocated to the customer."
      type: array
      items:
        $ref: '#/components/schemas/urn_samm_io.catenax.product_stock_1.0.0_Position'
    urn_samm_io.catenax.product_stock_1.0.0_MaterialNumber:
      type: string
      description: "The material number is a multi-character string, usually assigned\
        \ by an ERP system."
    urn_samm_io.catenax.product_stock_1.0.0_CatenaXIdTraitCharacteristic:
      type: string
      description: "The provided regular expression ensures that the UUID is composed\
        \ of five groups of characters separated by hyphens, in the form 8-4-4-4-12\
        \ for a total of 36 characters (32 hexadecimal characters and 4 hyphens),\
        \ optionally prefixed by \"urn:uuid:\" to make it an IRI."
      pattern: "(^[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)|(^urn:uuid:[0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{4}-[0-9a-fA-F]{12}$)"
    ProductStock:
      description: |
        This aspect represents the latest quantities of a supplier's products that are on stock. The stock represent the build-to-order (BTO) stocks already available for the customer.
      type: object
      properties:
        positions:
          description: "The positions refer to positions within an order that refer\
            \ to the given product (see materialNumberSupplier, materialNumberCustomer\
            \ and materialNumberDataSpace) for which the stocks are transferred. The\
            \ positions are differentiated by the orderPositionReference."
          $ref: '#/components/schemas/urn_samm_io.catenax.product_stock_1.0.0_PositionsCollection'
        materialNumberCustomer:
          description: "Material identifier as assigned by customer. This material\
            \ number identifies the material (as planned) in customer's database.\
            \ For standard parts (e.g. screws) for which a customer does not have\
            \ an own number, the materialNumberSupplier should be set in this field,\
            \ too."
          $ref: '#/components/schemas/urn_samm_io.catenax.product_stock_1.0.0_MaterialNumber'
        materialNumberCatenaX:
          description: Material identifier used uniquely within Catena-X to identify
            the Material (e.g. PartAsPlanned).
          $ref: '#/components/schemas/urn_samm_io.catenax.product_stock_1.0.0_CatenaXIdTraitCharacteristic'
        materialNumberSupplier:
          description: Material identifier as assigned by supplier. This material
            number identifies the material (as planned) in supplier's database.
          $ref: '#/components/schemas/urn_samm_io.catenax.product_stock_1.0.0_MaterialNumber'
      required:
      - positions
      - materialNumberCustomer
  responses:
    Unauthorized:
      description: The requesting user or client is not authenticated.
    Forbidden:
      description: The requesting user or client is not authorized to access resources
        for the given tenant.
    NotFoundError:
      description: The requested Twin has not been found.
    ClientError:
      description: Payload or user input is invalid. See error details in the payload
        for more.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    ProductStock:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/PagingSchema'
      description: The request was successful.
  requestBodies:
    ProductStock:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ProductStock'
